### ISSUE TITLE
Replace gravatar with refile

### ISSUE THREAD

**Issue by bodrovis** [bodrovis/SitePoint-Mailboxer#1]
As per this discussion https://github.com/mailboxer/mailboxer/issues/332#issuecomment-71554411

**Comment by bodrovis** [comment]
Well, I've started working on that but refile requires Ruby 2.1.0 or higher and currently I do not have a possibility to install that. Hopefully will be done in the next few days.

**Comment by RailsCod3rFuture** [comment]
Sounds great, thanks!

**Comment by bodrovis** [comment]
Seems like I won't be able to implement it any time soon because of this https://github.com/elabs/refile/issues/133. If you have your project somewhere on GitHub I can look at it and maybe pinpoint some mistakes.

**Comment by RailsCod3rFuture** [comment]
I'll probably use paperclip for the time being. I thought refile would be a sure shot given the documentation on it. I'm using a private git on my home based server. What I will do is create a paid account here, and let you access the project that way. I'll contact you again when everything is set and ready to go.

**Comment by bodrovis** [comment]
Closing as per this comment https://github.com/refile/refile/issues/133#issuecomment-76607745 
I also have no possibility to look into this problem any time soon.
