### ISSUE TITLE
Inbox count Mailboxer 

### ISSUE THREAD

**Issue by ajazshaik** [bodrovis/SitePoint-Mailboxer#10]
How to display my gmail inbox count in rails app

just want to display of my gmail inbox  badge with count in rails app
![untitled](https://cloud.githubusercontent.com/assets/18135790/17395659/3edf8b1c-5a4d-11e6-8fd6-416a69b88f5c.png)

**Comment by bodrovis** [comment]
This can be solved, but requires additional work. Probably I can work on this, let me know if this still an issue by contacting via e-mail.

**Comment by ajazshaik** [comment]
hi ilya
can u help us to get incoming mail using mailgun

Thanks & Regards
ajaz
