### ISSUE TITLE
Add unread counts to the nav-pills

### ISSUE THREAD

**Issue by Frank004** [bodrovis/SitePoint-Mailboxer#4]
Hi how can I add this code 

```
  <%= current_user.mailbox.inbox(:unread => true).count %>
```

for counting unread messages to inbox nav-pill and add icons to thnk you

**Comment by bodrovis** [comment]
For that you'll have to work with reciepts, not with an inbox. I haven't hacked with that a lot, but judging by this https://github.com/mailboxer/mailboxer/blob/cde8b2847a5600256c8aa161f68e22c34603ef8b/app/models/mailboxer/receipt.rb#L31 there is an `is_unread` scope for receipts. Therefore this

``` ruby
current_user.reciepts.is_unread.count
```

will do the trick.

**Comment by bodrovis** [comment]
I've also found this one https://github.com/mailboxer/mailboxer/blob/54277d6971af71c04bf50f5599e8efcba9f5ee60/lib/mailboxer/models/messageable.rb#L54 which means

``` ruby
current_user.unread_inbox_count
```

**Comment by Frank004** [comment]
![screen shot 2015-02-10 at 4 06 57 pm](https://cloud.githubusercontent.com/assets/7242689/6135535/db864eaa-b13f-11e4-98de-f6b96fdb5954.jpg)
yes I got it to work the thing i dnt know is how to add it on the pill so its display like thi img Inbox(0)

**Comment by bodrovis** [comment]
Well, just use `<%= %>` to add that in the view. For such general questions I'd recommend browsing some tutorials or StackOverflow, as in most cases it helps.

**Comment by Frank004** [comment]
thank you I got it working :)
