### ISSUE TITLE
Receiving a NoMethodError mailbox for <User::0x>

### ISSUE THREAD

**Issue by RailsCod3rFuture** [bodrovis/SitePoint-Mailboxer#5]
Hello Bodrovis, I'm currently having an issue with the mailboxer solution that you created. I can't seem to get the mailbox for a new user. I'm receiving this error directly below.

NoMethodError (undefined method `mailbox' for #<User:0xacdd8b8>):
  app/controllers/conversations_controller.rb:58:in`get_mailbox'

Even though, the method itself is correct?

def get_mailbox
    @mailbox ||= current_user.mailbox
  end

Processing by ConversationsController#index as HTML
  User Load (0.0ms)  SELECT  "users".\* FROM "users" WHERE "users"."id" = ?  ORDER BY "users"."id" ASC LIMIT 1  [["id", 2]]
Completed 500 Internal Server Error in 4ms

The console is showing 'missing_method' 

Also, I can't seem to get mailboxer to work for both user models :user and :biz_user.

**Comment by bodrovis** [comment]
That's hard to say without seeing the actual code. Does this error appear for all users?

**Comment by RailsCod3rFuture** [comment]
acts_as_messageable was missing from the user models. I didn't realize it until I read through the entire file. Which is fairly large now. Other than that, can you help me allow the two user models to communicate? :user and :biz_user

**Comment by RailsCod3rFuture** [comment]
I'm getting redirected when I attempt to access the ConversationsController as a business user? It's literally forcing me to sign in as a normal user on the redirect while the biz user is still logged in. It's strange.

Processing by ConversationsController#index as HTML
  BizUser Load (0.0ms)  SELECT  "biz_users".\* FROM "biz_users" WHERE "biz_users"."id" = ?  ORDER BY "biz_users"."id" ASC LIMIT 1  [["id", 5]]
Completed 401 Unauthorized in 3ms

**Comment by bodrovis** [comment]
Well, I might have time to look into this, but I can't promise because these days I have pretty high load. Meanwhile you can browse or ask a question on StackOverflow.

**Comment by RailsCod3rFuture** [comment]
If you could add in the multiple user model support using a branch. That would be great. I don't know if you consider it to be too much of a hassle. But, I'd like to get both models communicating and accessing their inboxes properly. I was searching everywhere for a working solution. Since, mailboxer is pretty much already built.

**Comment by bodrovis** [comment]
I believe I will try to research this issue and write a separate article. Can't say exactly when it will be published as there are some other articles in my pipeline atm. Still this should be an interesting topic.
