### ISSUE TITLE
reply_to_conversation

### ISSUE THREAD

**Issue by cotorusso** [bodrovis/SitePoint-Mailboxer#6]
```
current_user.reply_to_conversation(@conversation, params[:body]).conversation
```

generate this error:

> wrong number of arguments (1 for 0)

can you help me?

**Comment by bodrovis** [comment]
Hello. Of course, let's look into this issue.

I'll need full error stack trace to understand more.

By the way, if you were following my guide and have the same methods/controllers, then this line (in the `reply` method) is a bit different: https://github.com/bodrovis/SitePoint-Mailboxer/blob/9776ffe20ab596f6e804f35f670a68ac8766e5b2/app/controllers/conversations_controller.rb#L29
