### ISSUE TITLE
username & password demo site

### ISSUE THREAD

**Issue by mirzalazuardi** [bodrovis/SitePoint-Mailboxer#7]
hello @bodrovis i want to test your demo, can i have your username & password on http://sitepoint-mailboxer.herokuapp.com/users/sign_in . thanks

**Comment by bodrovis** [comment]
@mirzalazuardi Yes, you can :) Choose any here http://sitepoint-mailboxer.herokuapp.com/users/sign_up

**Comment by mirzalazuardi** [comment]
:+1: thanks @bodrovis . i just realised your repository made using devise.
