### ISSUE TITLE
Messaging with Rails and Mailboxer

### ISSUE THREAD

**Issue by ajazshaik** [bodrovis/SitePoint-Mailboxer#9]
Thanks for your reply, can u update the tutorial with rails 5

**Comment by bodrovis** [comment]
Well, I might do that, but I have to discuss with my editor. Sitepoint has some rules about which articles to publish and when - currently there are some other posts in my pipeline, so can't guarantee anything. If you need some personal help, that's totally possible - contact me via e-mail.
